import { CronJob } from 'cron';
import { getGateway } from '../lib/gateway';
import fs from 'fs';
import * as path from 'path';
import { parse } from 'csv-parse';
import { chaincodeName, channelName } from '../lib/constants';
import { LogDto } from '../lib/log-dto';
import { spawnSync } from 'child_process';

function getMacAddress(ip: string) {
  // Get all ARP processes
  const processes = spawnSync('arp', ['-n'], {
    encoding: 'utf-8',
  });

  if (processes.stderr) {
    throw new Error(processes.stderr);
  }

  // Get the table row containing the specific IP
  const process = spawnSync('grep', [ip], {
    input: processes.stdout,
    encoding: 'utf-8',
  });
  if (process.stderr) {
    throw new Error(process.stderr);
  }

  // Get the mac address
  const macAddress = spawnSync('awk', ['{print $3}'], {
    input: process.stdout,
    encoding: 'utf-8',
  });
  if (macAddress.stderr) {
    throw new Error(macAddress.stderr);
  }

  return macAddress.stdout.trim();
}

async function getLogs(): Promise<LogDto[]> {
  const logFileDir = path.resolve(
    __dirname,
    '..',
    '..',
    'snort-log',
    'log.csv',
  );

  const isLogDir = fs.existsSync(logFileDir);
  if (!isLogDir) {
    throw new Error('The log file has not been generated by Snort');
  }

  const logs: LogDto[] = [];
  const headers = [
    'timestamp',
    'protocol',
    'message',
    'srcAddress',
    'srcPort',
    'dstAddress',
    'dstPort',
  ];
  const logParse = fs
    .createReadStream(logFileDir)
    .pipe(parse({ delimiter: ',', columns: headers }));

  for await (const log of logParse) {
    if (!log.protocol) continue;

    const tRegrex = /^(\d{2})\/(\d{2})\/(\d{2})/;
    if (!tRegrex.test(log.timestamp)) continue;

    const uLog = {
      ...log,
      timestamp: log.timestamp.trim(),
      srcMacAddress: getMacAddress(log.srcAddress),
    } as LogDto;

    logs.push(uLog);
  }

  console.log('Logs: ', logs);
  fs.truncateSync(logFileDir);

  return logs;
}

async function createLogs(org: string): Promise<void> {
  const gateway = await getGateway(org);

  try {
    // Get a network instance representing the channel where the smart contract is deployed.
    const network = gateway.getNetwork(channelName);

    // Get the smart contract from the network.
    const contract = network.getContract(chaincodeName);

    const logs = await getLogs();
    if (logs.length === 0) return;

    await contract.submitTransaction(
      'createLogs',
      Buffer.from(JSON.stringify(logs)),
    );

    console.log('createLogs function is executed successfully');
  } catch (error) {
    console.error('Error in createLogs:', error);
  }
}

// The function gets network logs every 6 seconds and upload them to the blockchain ledger.
CronJob.from({
  cronTime: '*/10 * * * * *',
  onTick: () => {
    createLogs('org1');
  },
  start: true,
  timeZone: 'Asia/Ho_Chi_Minh',
});
